name: asynchrony
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  async: ^2.11.0
  dio: ^5.4.0
  http: ^1.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
